
#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'

networks:
  pbc_network:
    external: true

services:
  app:
    container_name: user
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - pbc_network
    command: >
      ash -c "air"
