
#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'
networks:
  basic:

services:
  app:
    container_name: user
    build: .
    tty: true
    command: sh
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - basic

  # mysql:
  #   image: mysql:8.0.21
  #   container_name: mysql
  #   ports:
  #   - 3306:3306
  #   restart: always
  #   volumes:
  #     - ./src/SP/mysql/mysql_data:/var/lib/mysql
  #     - ./src/SP/mysql/mysql_conf/:/etc/mysql/conf.d
  #   environment:
  #     MYSQL_DATABASE: sample_db
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: password
  #   command: mysqld --explicit_defaults_for_timestamp=true
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10
  
  # nginx:
  #     container_name: nginx
  #     build: ./nginx
  #     volumes:
  #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     ports:
  #         - 80:80
  #     restart: always 
  #     depends_on:
  #         - user
  #     networks:
  #         - basic